core/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'core'
urlpatterns = [
    url('^$', views.login),
    url(r'^map/$', views.MapView.as_view(), name="map"),
    url(r'^events/$', views.EventsView.as_view(), name="events"),
    url(r'^events/api', views.EventViewSet.as_view()), 
    url(r'^events/(?P<event_id>[0-9]+)/member$', views.EventMemberView.as_view(), name="event_join"),
    url(r'^events/(?P<pk>[0-9]+)/$', views.EventView.as_view(), name="event"),
    # url(r'^profile/$', views.ProfileView.as_view(), name="profile"),
    url(r'^profile/(?P<pk>[0-9]+)/$', views.ProfileView.as_view(), name="profile"),
    url(r'^profile/save_location$', views.UserUpdateLocationView.as_view(), name="save_location"),
    url(r'^tag/create$', views.TagCreateView.as_view(), name="tag_create"),
]

pinned/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from rest_framework import routers

from core import views

# Route to events api endpoint
router = routers.DefaultRouter()
router.register(r'users/api', views.UserViewSet)
router.register(r'tags/api', views.TagViewSet)

urlpatterns = [
    url(r'^', include('core.urls')),
    url(r'^', include(router.urls)),
    url(r'^', include('django.contrib.auth.urls', namespace='auth')),
    url(r'^', include('social_django.urls', namespace='social')),
    url(r'^admin/', admin.site.urls),
]

core/forms.py
from django import forms
from .models import Event
from django.core.exceptions import ValidationError
from django.utils import timezone


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        exclude = ['participants', 'event_owner']
        widgets = {'latitude': forms.HiddenInput(),
                   'longitude': forms.HiddenInput(),
                   'description': forms.Textarea(),
                   'start_date_time': forms.TextInput(attrs={'class': 'date-time-picker'}),
                   'end_date_time': forms.TextInput(attrs={'class': 'date-time-picker'}),
                   'tag': forms.Select(),
                   }

    def clean(self):
        cleaned_data = super(EventForm, self).clean()
        start_date_time = cleaned_data.get("start_date_time")
        end_date_time = cleaned_data.get("end_date_time")

        if start_date_time and end_date_time:
            if start_date_time < timezone.now():
                raise ValidationError("Start time cannot be prior to the current time!")

            if end_date_time < start_date_time:
                raise ValidationError("End time cannot be earlier than start time!")
        else:
            raise ValidationError("Missing date and time for the event!")
        return cleaned_data

core/views/decorators.py
from django.contrib.auth.decorators import login_required

login_decorator = login_required(login_url='/', redirect_field_name=None)

core/views/event_member_view.py
import json

from django.views import generic
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError
from django.http import HttpResponse
from django.utils import timezone

from ..models import Event, Join
from .decorators import login_decorator

# View that allows users to join or leave events
class EventMemberView(generic.View):

    @method_decorator(login_decorator)
    def post(self, request, *args, **kwargs):
        event_id = self.kwargs['event_id']
        action = request.POST['action']

        data = {}
        action_word = 'performed an invalid action on'

        try:
            event = Event.objects.get(pk=event_id)
            if action == 'join':
                action_word = 'joined'
                n_participants = len(event.participants.all())

                if n_participants >= event.max_num_participants: 
                    raise IntegrityError("max_num_participants reached")
                else:
                    join_date = timezone.now
                    Join.objects.create(user=request.user, event=event, join_date=join_date)
            elif action == 'leave':
                action_word = 'left'

                Join.objects.filter(user=request.user, event=event).delete()

            data['result'] = True
            data['participants'] = [{'name': p.first_name, 'id': p.id} for p in event.participants.all()]

            print("{} {} {}".format(request.user, action_word, event))

        except IntegrityError as e:
            print("[Warning] Exception during " + action)
            print(str(e))
            data['result'] = False
        
        return HttpResponse(json.dumps(data))

core/views/event_view.py
from django.views import generic
from django.utils.decorators import method_decorator

from ..models import Event, Join

from .decorators import login_decorator
from .utils import get_user_notifications

@method_decorator(login_decorator, name='get')
class EventView(generic.DetailView):
    template_name = 'core/pages/event.html'
    model = Event

    def get_context_data(self, **kwargs):
        user_id = self.request.user.id
        context = super(EventView, self).get_context_data(**kwargs)
        context['joined'] = Join.objects.filter(user__pk=user_id, event__pk=self.kwargs['pk']).exists()

        context['notifications'] = get_user_notifications(self.request.user)
        return context    

core/views/event_viewset.py
from datetime import datetime
from django.utils import timezone
from django.utils import dateparse

from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response

from ..models import Event, User, Tag
from ..serializers import EventSerializer


class EventViewSet(APIView):

    def get(self, request, *args, **kwargs):
        # Get all events that have not ended yet
        queryset = Event.objects.filter(end_date_time__gt=timezone.now())

        # Obtain the list of user scopes (interests, single tag, text filtering and date filtering)
        scopes = request.GET.getlist('scopes[]')
        
        # Filter on user's interests
        if 'interests' in scopes:
            user_id = request.user.id
            user = User.objects.get(pk=user_id)
            tags = user.interest_tags.all()

            queryset = queryset.filter(tag__in=tags)

        # Filter to just one tag
        elif 'tag' in scopes:
            selected_tag = request.GET['tag']
            tag = Tag.objects.get(name=selected_tag)

            queryset = queryset.filter(tag=tag)

        # Filter by text contained in event name
        if 'name' in scopes:
            text = request.GET['text']

            queryset = queryset.filter(name__icontains=text)
        
        # Filter by start date
        if 'date' in scopes:
            date = request.GET['date']
            datetime_object = timezone.make_aware(datetime.strptime(date, '%m/%d/%y'))

            queryset = queryset.filter(start_date_time__gt=datetime_object)

        serializer_class = EventSerializer(queryset, many=True, context={'request': request})

        return Response(serializer_class.data)

core/views/events_view.py
from django.views import generic
from django.utils.decorators import method_decorator

from ..models import Event, Join

from .decorators import login_decorator
from .utils import get_user_notifications

@method_decorator(login_decorator, name='get')
class EventsView(generic.ListView):
    template_name = 'core/pages/events.html'
    model = Event

    def get_context_data(self, **kwargs):  # Add field names to the context
        context = super(EventsView, self).get_context_data(**kwargs)
        joined_events = {}
        user_id = self.request.user.id
        for event in context['event_list']:
            exists = Join.objects.filter(user__pk=user_id, event__pk=event.id).exists()
            if exists:
                joined_events[event.id] = True
        context['fields'] = Event._meta.get_fields()
        context['joined_events'] = joined_events

        context['notifications'] = get_user_notifications(self.request.user)
        return context

core/views/map_view.py
from math import sin, cos, radians, degrees, acos 

from django.views import generic
from django.shortcuts import render
from django.utils import timezone
from django.utils.decorators import method_decorator

from ..models import Event, User, NotificationEvent, UserNotification
from ..forms import EventForm

from .decorators import login_decorator
from .utils import get_user_notifications


class MapView(generic.View):

    @staticmethod
    def get_default_context():
        now = timezone.now()
        context = {
            "event_list": Event.objects.filter(end_date_time__gt=now, start_date_time__gt=now)
                                       .order_by('start_date_time')[:3]
            }
        return context

    @method_decorator(login_decorator)
    def post(self, request):

        self.context = MapView.get_default_context()

        def create_event_notification(event):

            def distance(user, event):
                user_lat = radians(user.latitude)
                event_lat = radians(event.latitude)
                longitude_diff = radians(user.longitude - event.longitude)
                dist = (sin(user_lat) * sin(event_lat) + cos(user_lat) * cos(event_lat) * cos(longitude_diff))
                return degrees(acos(dist)) * 69.09

            # Create notification for every participant
            if event.tag is not None:
                for user in User.objects.filter(interest_tags__name__contains=event.tag.name).exclude(pk=request.user.pk):
                    # Check if user is less than or equal to 15 miles away from created event
                    if user.latitude is not None and user.longitude is not None and distance(user, event) <= 15:
                        # Create notification
                        notification = NotificationEvent(date=timezone.now(), event=event, user=user)
                        notification.save()

                        # Create link user-notification in the notification interface
                        user_notification = UserNotification(content_object=notification, user=user,
                                                             object_id=notification.id)
                        user_notification.save()

        try:
            form_temp = EventForm(request.POST)
            form = form_temp.save(commit=False)
            form.event_owner = request.user
            form.save()
            form_temp.save_m2m() # Needed for saving tags, added by using "commit=False"
            self.context['state'] = "saved"
            create_event_notification(form)
            self.context['notifications'] = get_user_notifications(request.user)
        except ValueError as e:
            self.context['state'] = "error"
            self.context['errors'] = form_temp.errors
            self.context['other_errors'] = form_temp.non_field_errors()
            print(e)

        self.context['form'] = EventForm()
        return render(request, 'core/pages/map.html', context=self.context)

    def get(self, request, *args, **kwargs):

        self.context = MapView.get_default_context()
        self.context['state'] = "get"
        if request.user.is_authenticated():
            self.context['form'] = EventForm()
            user_id = request.user.id
            user = User.objects.get(pk=user_id)
            tags = user.interest_tags.all()
            self.context['tags'] = tags
            self.context['notifications'] = get_user_notifications(user)
            self.context.pop('not_logged_in', None)
        else:
            self.context['not_logged_in'] = True
        return render(request, 'core/pages/map.html', context=self.context)

core/views/profile_view.py
import json
from django.views import generic
from django.utils.decorators import method_decorator
from django.http import HttpResponse

from ..models import User, Join, Event, Tag

from .decorators import login_decorator
from .utils import get_user_notifications

@method_decorator(login_decorator, name='get')
class ProfileView(generic.DetailView):
    
    template_name = 'core/pages/profile.html'
    model = User

    def get_context_data(self, **kwargs):
        user = User.objects.filter(pk=self.kwargs['pk'])[0]

        joined_events_id = list(Join.objects.filter(user=user).values_list('event', flat=True))        
        joined_events = list(Event.objects.filter(id__in=joined_events_id).exclude(event_owner=user))
        
        owned_events  = list(Event.objects.filter(event_owner=user))
                
        tags = Tag.objects.order_by('name') 
        interests = user.interest_tags.all()

        context = {'user': user,
                   'joined_events': joined_events,
                   'owned_events': owned_events,
                   'tags': tags,
                   'interests': interests,
                   'notifications': get_user_notifications(self.request.user),
                   'same_user': user == self.request.user}
        return context

    def post(self, request, *args, **kwargs):
        data = {}
        user = User.objects.filter(pk=self.kwargs['pk'])[0]
        if user != request.user:
          data['result'] = False
        else:
          tag_ids = map(int, request.POST.getlist('selectedTags[]'))        
          tags = Tag.objects.filter(pk__in=tag_ids)
          user.interest_tags = tags
          
          data['result'] = True

        return HttpResponse(json.dumps(data))

core/views/tag_create_view.py
import random
import string
import json

from django.views import generic
from django.db.utils import IntegrityError
from django.http import HttpResponse
from django.utils.decorators import method_decorator

from ..models import Tag

from .decorators import login_decorator


@method_decorator(login_decorator, name='post')
class TagCreateView(generic.View):

    def post(self, request, *args, **kwargs):
        tag_name = request.POST['tagName']
        color = ''.join(random.choice(string.hexdigits) for _ in range(6))
        try:
            tag = Tag.objects.create(name=tag_name, color=color)
        except IntegrityError:
            tag = {'id': -1}

        return HttpResponse(json.dumps({'id': tag.id}))

core/views/tag_viewset.py
from rest_framework import viewsets
from ..models import Tag
from ..serializers import TagSerializer

# Enables access to all tags
class TagViewSet(viewsets.ModelViewSet):
    queryset = Tag.objects.all()
    serializer_class = TagSerializer

core/views/user_update_location_view.py
from django.views import generic
from django.http import HttpResponse
from django.utils.decorators import method_decorator

from .decorators import login_decorator

@method_decorator(login_decorator, name='post')
class UserUpdateLocationView(generic.View):
    def post(self, request, *args, **kwargs):
        user = request.user
        response = None
        try:
            latitude = float(request.POST['lat'])
            longitude = float(request.POST['long'])
            user.latitude = latitude
            user.longitude = longitude
            user.save()
            response = HttpResponse('success')
            response.status_code = 200
        except ValueError:
            response = HttpResponse('failure')
            response.status_code = 400
        return response

core/views/user_viewset.py
from rest_framework import viewsets
from ..models import User
from ..serializers import UserSerializer

# Enables access to all user profiles
class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer

core/views/utils.py
from ..models import UserNotification

def get_user_notifications(user):
    notifications = UserNotification.objects.filter(user=user)
    result = [notification.content_object for notification in notifications]
    return result

core/templates/core/partials/event_card.html
<div class="col-sm-4">
    <div class="card event-card {% if owner == 'me' %} my-event {% else %} other-event {% endif %} mb-3" style="max-width: 20rem;">
        <a class="event-card-link" href="/events/{{ event.id }}/">
            <div class="card-header">
                <h4> {{ event.name }} </h4> {{ event.start_date_time }}
            </div>
            <div class="card-body">
                <p class="card-owner">Created by {{ event.event_owner.first_name }} </p>
            </div>
        </a>
    </div>
</div>

core/templates/core/partials/event_form.html
<div id="event-output">
    {% if state == "saved" %}
    <div class="alert alert-success" role="alert">
        Event succesfully created!
    </div>
    {% elif state == "error" %}
    <div class="alert alert-danger" role="alert">
        {% if errors.name %}
            Error in <span class="error-name">event name</span>: <span class="error-desc">{{ errors.name.0 }}</span><br>
        {% endif %}
        {% if errors.description %}
            Error in <span class="error-name">event description</span>: <span class="error-desc">{{ errors.description.0 }}</span><br>
        {% endif %}
        {% if errors.tags %}
            Error in <span class="error-name">tags</span>: <span class="error-desc">{{ errors.tags.0 }}</span><br>
        {% endif %}
        {% if errors.max_num_participants %}
            Error in <span class="error-name">maximum number of participants</span>: <span class="error-desc">{{ errors.max_num_participants.0 }}</span><br>
        {% endif %}
        {% if errors.latitude %}
            Error in <span class="error-name">latitude</span>: </span><span class="error-desc">{{ errors.latitude.0 }}</span><br>
        {% endif %}
        {% if errors.longitude %}
            Error in <span class="error-name">longitude</span>: <span class="error-desc">{{ errors.longitude.0 }}</span><br>
        {% endif %}
        {% if errors.start_date_time %}
            Error in <span class="error-name">start date</span>: <span class="error-desc">{{ errors.start_date_time.0 }}</span><br>
        {% endif %}
        {% if errors.end_date_time %} 
            Error in <span class="error-name">end date</span>: <span class="error-desc">{{ errors.end_date_time.0 }}</span><br>
        {% endif %}
        {% if other_errors %}
            Error in <span class="error-name">start and end date</span>: <span class="error-desc">{{ other_errors.0 }}</span><br>
        {% endif %}

    </div>
    {% else %} {% endif %}
</div>
<div id="event-input" class="invisible d-flex align-items-center justify-content-center">
    <form id="event-form" action="/map/" method="post">
        <h1>Create new event</h1>
        {% csrf_token %} {{ form.as_p }}
        <div class="date-times form-row"></div>
        <div class="d-flex flex-row-reverse order-last">
            <button type="submit" class="btn btn-submit btn-primary">Submit</button>
            <button type="button" class="btn btn-cancel btn-danger">Cancel</button>
        </div>
    </form>
</div>

core/templates/core/partials/map_filters.html
<form id="map-filters">
  <div class="container">
    <div class="row">
      <div class="col-sm-4">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-futbol-o" data-toggle="dropdown" aria-hidden="true"></i></span>
          <div class="dropdown form-control" style="padding: 0;">
          <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="width: 100%; border-radius: 0;">
            All Events
          </button>
          <div id="filter-dropdown" class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="#">All Events</a>
              <a class="dropdown-item" href="#">My Interests</a>
            {% for tag in tags %}
              <a class="dropdown-item" href="#">{{ tag.name }}</a>
            {% endfor %}
          </div>
        </div>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="input-group">
          <span class="input-group-addon"><i class="fa fa-search" aria-hidden="true"></i></span>
          <input id="filter-search" type="text" class="form-control"/>
        </div>
      </div>
      <div class="col-sm-4">
        <div class="input-group" id="datepicker">
          <span class="input-group-addon"><i class="fa fa-calendar" aria-hidden="true"></i></span>
          <input id="filter-date" class="form-control"/>
        </div>
      </div>
    </div>
  </div>
</form>

core/templates/core/partials/nav.html
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'core:map' %}">Pinned <i class="fa fa-map-marker" aria-hidden="true"></i></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:events' %}" title="Events list">Events</a>
            </li>
        </ul>
        {% if not not_logged_in %}
        <ul class="navbar-nav">
            <li class="nav-item">
                <div class="notifications dropdown">
                    <a class="dropdown-toggle nav-link" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Notifications
                  </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        {% if notifications %}
                            {% for notif in notifications %} {% include "core/partials/notification.html" with notification=notif %} {% endfor %}
                        {% else %}
                            <center>No notifications</center>
                        {% endif %}
                    </div>
                </div>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'core:profile' pk=request.user.pk %}" title="User profile">Profile</a>
            </li>
        </ul>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="/logout" title="Logout">Logout</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>

core/templates/core/partials/notification.html
<a class="dropdown-item" href="/events/{{ notification.event.id }}/">
    {{ notification.event.name }}
    {{ notification.text }}
</a>

core/templates/core/partials/rating_form.html
<div id = "rating-form">
    <h1>How would you rate this user?</h1>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1,width=device-width">
    <link rel="stylesheet" href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <x-star-rating value="0" number="5"></x-star-rating>

    <form id="rating_form" method="post" action="/rate/">
        {% csrf_token %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            <br>
            <div>
                {{ field }}
            </div>
        {% endfor %}
        <div>
            <input type="submit" name="submit" value="Submit rating"/>
        </div>
    </form>
</div>

core/templates/core/partials/save_token.html
<script type="text/javascript">
window.token = '{{ csrf_token }}'
</script>

core/templates/core/partials/upcoming_events.html
<h2 class="text-center">Upcoming events...</h2>
<div class="row">
    {% for event in event_list %}
      {% include "core/partials/event_card.html" with owner="others" %}
    {% endfor %}
</div>